export const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const ICONS={
 home:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10.8 12 3l9 7.8v9.2a1 1 0 0 1-1 1h-5.5v-6h-5v6H4a1 1 0 0 1-1-1z"/></svg>`,
 hymns:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/></svg>`,
 bible:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4.5A2.5 2.5 0 0 1 7.5 2H20v17H7.5A2.5 2.5 0 0 0 5 21.5z"/><path d="M5 4.5v17M8 6h8M8 10h8M8 14h5"/></svg>`,
 settings:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z"/><path d="m19.4 15 .1.1a1.7 1.7 0 0 1-2.4 2.4l-.1-.1a7.8 7.8 0 0 1-2.1 1.2v.2a1.7 1.7 0 0 1-3.4 0v-.2a7.8 7.8 0 0 1-2.1-1.2l-.1.1a1.7 1.7 0 1 1-2.4-2.4l.1-.1A7.8 7.8 0 0 1 5.8 13h-.2a1.7 1.7 0 0 1 0-3.4h.2a7.8 7.8 0 0 1 1.2-2.1l-.1-.1a1.7 1.7 0 1 1 2.4-2.4l.1.1A7.8 7.8 0 0 1 11.5 4v-.2a1.7 1.7 0 0 1 3.4 0V4a7.8 7.8 0 0 1 2.1 1.2l.1-.1a1.7 1.7 0 1 1 2.4 2.4l-.1.1a7.8 7.8 0 0 1 1.2 2.1h.2a1.7 1.7 0 0 1 0 3.4h-.2a7.8 7.8 0 0 1-1.2 2.1Z"/></svg>`
};
export function toast(s){const x=document.createElement("div");x.className="toast";x.textContent=s;document.body.append(x);setTimeout(()=>x.remove(),2200)}

let dialogStylesReady=false;
function ensureDialogStyles(){if(dialogStylesReady)return;dialogStylesReady=true;const st=document.createElement("style");st.textContent=`
.hco-dialog{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(20,31,48,.48);backdrop-filter:blur(3px)}
.hco-dialog-card{width:min(100%,430px);background:#fff;border-radius:18px;padding:20px;box-shadow:0 18px 50px rgba(0,0,0,.22);border:1px solid rgba(35,64,106,.12)}
.hco-dialog-title{font-size:19px;font-weight:800;color:#23406A;margin-bottom:8px}
.hco-dialog-message{white-space:pre-line;color:#5b6573;font-size:14px;line-height:1.5;margin-bottom:14px}
.hco-dialog-input{width:100%;box-sizing:border-box;border:1px solid #ccd5e1;border-radius:10px;padding:11px 12px;font:inherit;outline:none;background:#f9fafc;color:#1f2937}
.hco-dialog-input:focus{border-color:#23406A;box-shadow:0 0 0 3px rgba(35,64,106,.12)}
.hco-dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}
.hco-dialog-actions .btn{min-width:92px}
`;document.head.append(st)}
export function appPrompt(title,message="",value="",options={}){ensureDialogStyles();return new Promise(resolve=>{const wrap=document.createElement("div");wrap.className="hco-dialog";const multiline=options.multiline===true;wrap.innerHTML=`<div class="hco-dialog-card" role="dialog" aria-modal="true"><div class="hco-dialog-title">${esc(title)}</div>${message?`<div class="hco-dialog-message">${esc(message)}</div>`:""}${multiline?`<textarea class="hco-dialog-input" rows="5"></textarea>`:`<input class="hco-dialog-input" type="text">`}<div class="hco-dialog-actions"><button class="btn" data-cancel>${esc(options.cancelText||"Cancelar")}</button><button class="btn primary" data-ok>${esc(options.confirmText||"Aceptar")}</button></div></div>`;document.body.append(wrap);const input=wrap.querySelector(".hco-dialog-input");input.value=value??"";const finish=result=>{wrap.remove();resolve(result)};wrap.querySelector("[data-cancel]").onclick=()=>finish(null);wrap.querySelector("[data-ok]").onclick=()=>finish(input.value);wrap.addEventListener("click",e=>{if(e.target===wrap)finish(null)});input.addEventListener("keydown",e=>{if(e.key==="Escape"){e.preventDefault();finish(null)}else if(e.key==="Enter"&&!multiline){e.preventDefault();finish(input.value)}});requestAnimationFrame(()=>{input.focus();input.select()})})}
export function appConfirm(title,message="",options={}){ensureDialogStyles();return new Promise(resolve=>{const wrap=document.createElement("div");wrap.className="hco-dialog";wrap.innerHTML=`<div class="hco-dialog-card" role="dialog" aria-modal="true"><div class="hco-dialog-title">${esc(title)}</div>${message?`<div class="hco-dialog-message">${esc(message)}</div>`:""}<div class="hco-dialog-actions"><button class="btn" data-cancel>${esc(options.cancelText||"Cancelar")}</button><button class="btn danger" data-ok>${esc(options.confirmText||"Eliminar")}</button></div></div>`;document.body.append(wrap);const finish=result=>{wrap.remove();resolve(result)};wrap.querySelector("[data-cancel]").onclick=()=>finish(false);wrap.querySelector("[data-ok]").onclick=()=>finish(true);wrap.addEventListener("click",e=>{if(e.target===wrap)finish(false)});wrap.addEventListener("keydown",e=>{if(e.key==="Escape")finish(false)});requestAnimationFrame(()=>wrap.querySelector("[data-ok]").focus())})}
export function shell(title,active){document.getElementById("app").innerHTML=`<div class="app"><header class="top"><div class="topbar"><img class="brand" src="./assets/icons/icon-192.png"><strong>Himnario Cristiano</strong></div><h1>${esc(title)}</h1><div>100% offline</div></header><main id="view" class="content"></main><nav class="bottom" aria-label="Navegación principal">${[["home","Inicio"],["hymns","Himnos"],["bible","Biblia"],["settings","Ajustes"]].map(([r,t])=>`<button class="nav ${active===r?"active":""}" data-r="${r}" aria-label="${t}"><span class="nav-icon">${ICONS[r]}</span><span class="nav-label">${t}</span></button>`).join("")}</nav></div>`}
export function nav(go){document.querySelectorAll("[data-r]").forEach(x=>x.onclick=()=>go(x.dataset.r))}
